### ISSUE TITLE
/usr/bin/xdg-open: 801: /user/bin/xdg-open: : permission denied

### ISSUE THREAD

**Issue by graememilne** [neilnm/skyspy#1]
I have followed the instructions on your page.
then cd skypy
python3 skyspy.py

This opens dump1090 with 
webserver started
('127.0.01', 50957)
/usr/bin/xdg-open: 801: /user/bin/xdg-open: : permission denied
Then it finds the dongle opens up dump1090 and shows aircraft ( opens the skyspy.html but does not pass the aircrft info to it)
I suspect the error with xdg-open is the problem so how do i give permission to it ???

Thank you in advance 
Graeme

**Comment by neilnm** [comment]
Issue was fixed after reinstalling some dependencies, see: https://github.com/neilnm/skyspy/issues/2
