### ISSUE TITLE
/usr/bin/xdg-open: 801: /user/bin/xdg-open: : permission denied

### ISSUE THREAD

**Issue by graememilne** [neilnm/skyspy#2]
UPDATE

I uninstalled and installed xdg-utils several time .
 sudo apt-get purge xdg-utils 
 sudo apt-get install xdg-utils
 sudo apt-get update
 sudo apt-get upgrade 
At one point Dillo web browser appeared as i lost chromium browser
Reinstalled Chromium browser .
Restarted skyspy and now it is working
Probably did other updates too but can not remember which ones
Thank you for a brilliant piece of software

**Comment by neilnm** [comment]
Hey, glad it's working!
